# CMake generated Testfile for 
# Source directory: /home/cs104/cs104/hw-kim503/hw1/hw1_tests/flex_char_manager
# Build directory: /home/cs104/cs104/hw-kim503/hw1/hw1_tests/flex_char_manager
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(SecondMemtest.Execution "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/hw-kim503/hw1/hw1_tests/flex_char_manager/flex_char_manager_test" "--gtest_filter=SecondMemtest.Execution")
add_test(FlexCharManager.ConstructionDestruction "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/hw-kim503/hw1/hw1_tests/flex_char_manager/flex_char_manager_test" "--gtest_filter=FlexCharManager.ConstructionDestruction")
add_test(FlexCharManager.InvalidFree "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/hw-kim503/hw1/hw1_tests/flex_char_manager/flex_char_manager_test" "--gtest_filter=FlexCharManager.InvalidFree")
add_test(FlexCharManager.ZeroFill "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/hw-kim503/hw1/hw1_tests/flex_char_manager/flex_char_manager_test" "--gtest_filter=FlexCharManager.ZeroFill")
add_test(FlexCharManager.OneCharAlloc "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/hw-kim503/hw1/hw1_tests/flex_char_manager/flex_char_manager_test" "--gtest_filter=FlexCharManager.OneCharAlloc")
add_test(FlexCharManager.OneCharFree "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/hw-kim503/hw1/hw1_tests/flex_char_manager/flex_char_manager_test" "--gtest_filter=FlexCharManager.OneCharFree")
add_test(FlexCharManager.FiveCharAlloc "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/hw-kim503/hw1/hw1_tests/flex_char_manager/flex_char_manager_test" "--gtest_filter=FlexCharManager.FiveCharAlloc")
add_test(FlexCharManager.FiveCharAllocFree "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/hw-kim503/hw1/hw1_tests/flex_char_manager/flex_char_manager_test" "--gtest_filter=FlexCharManager.FiveCharAllocFree")
add_test(FlexCharManager.Alloc_x2 "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/hw-kim503/hw1/hw1_tests/flex_char_manager/flex_char_manager_test" "--gtest_filter=FlexCharManager.Alloc_x2")
add_test(FlexCharManager.AllocFree_x2_RevOrder "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/hw-kim503/hw1/hw1_tests/flex_char_manager/flex_char_manager_test" "--gtest_filter=FlexCharManager.AllocFree_x2_RevOrder")
add_test(FlexCharManager.AllocFree_x2_FwdOrder "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/hw-kim503/hw1/hw1_tests/flex_char_manager/flex_char_manager_test" "--gtest_filter=FlexCharManager.AllocFree_x2_FwdOrder")
add_test(FlexCharManager.MemoryReuse "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/hw-kim503/hw1/hw1_tests/flex_char_manager/flex_char_manager_test" "--gtest_filter=FlexCharManager.MemoryReuse")
add_test(FlexCharManager.Alloc10000Chars "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/hw-kim503/hw1/hw1_tests/flex_char_manager/flex_char_manager_test" "--gtest_filter=FlexCharManager.Alloc10000Chars")
add_test(FlexCharManager.Alloc5Charx2000 "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/hw-kim503/hw1/hw1_tests/flex_char_manager/flex_char_manager_test" "--gtest_filter=FlexCharManager.Alloc5Charx2000")
add_test(FlexCharManager.AllocDealloc10Charx1000 "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/hw-kim503/hw1/hw1_tests/flex_char_manager/flex_char_manager_test" "--gtest_filter=FlexCharManager.AllocDealloc10Charx1000")
add_test(FlexCharManager.RandomOrderDealloc "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/hw-kim503/hw1/hw1_tests/flex_char_manager/flex_char_manager_test" "--gtest_filter=FlexCharManager.RandomOrderDealloc")
add_test(FlexCharManager.BasicFirstFit "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/hw-kim503/hw1/hw1_tests/flex_char_manager/flex_char_manager_test" "--gtest_filter=FlexCharManager.BasicFirstFit")
add_test(FlexCharManager.IntermediateFirstFit "/usr/bin/valgrind" "--tool=memcheck" "--leak-check=yes" "--error-exitcode=42" "--trace-children=no" "/home/cs104/cs104/hw-kim503/hw1/hw1_tests/flex_char_manager/flex_char_manager_test" "--gtest_filter=FlexCharManager.IntermediateFirstFit")
